services:
 mongodata:
  image: coralproject/mongodata
  environment:
    - "MONGO_DUMP=https://s3.amazonaws.com/coral-demo-dataset/dump.tar.gz"
    - "MONGO_USER=${MONGO_USER}"
    - "MONGO_PASS=${MONGO_PASS}"
    - "MONGO_DB=${MONGO_DB}"
  volumes:
    - /mongodata:/data/db
  ports:
    - "27017"

rabbitmq:
  image: rabbitmq:management
  environment:
    - "RABBITMQ_DEFAULT_USER=${RABBIT_USER}"
    - "RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}"
  ports:
    - "15672:15672"
    - "5672:5672"

pillarapp:
   image: coralproject/pillar
   restart: always
   depends_on:
    - rabbitmq
   environment:
           - "PILLAR_HOME=/opt/pillar"
           - "PILLAR_ADDRESS=:8080"
           - "MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/${MONGO_AUTHDB}"
           - "AMQP_EXCHANGE=PillarMQ"
           - "PILLAR_CRON=false"
           - "PILLAR_CRON_SEARCH=@every 30m"
           - "PILLAR_CRON_STATS=@every 1m"
           - "XENIA_URL="http://xeniaapp:4000/1.0/exec/"
           - "XENIA_QUERY_PARAM=?skip=0&limit=100"
           - "XENIA_AUTH=<auth token>"
           - "AMQP_URL=amqp://${RABBIT_USER}:${RABBIT_PASS}@rabbitmq:5672/"
   ports:
       - "8080:8080"
   links:
      - mongodata
      - rabbitmq
atollapp:
   image: coralproject/atoll
   ports:
       - "8181:8181"
   links:
      - mongodata

xeniaapp:
   image: coralproject/xenia
   restart: always
   environment:
           - "XENIA_MONGO_HOST=mongodata:27017"
           - "XENIA_MONGO_AUTHDB=${MONGO_AUTHDB}"
           - "XENIA_MONGO_DB=${MONGO_DB}"
           - "XENIA_MONGO_USER=${MONGO_USER}"
           - "XENIA_MONGO_PASS=${MONGO_PASS}"
           - "XENIA_LOGGING_LEVEL=1"
           - "XENIA_HOST=:4000"
           - "XENIA_CREATE_DATABASE=${XENIA_CREATE_DATABASE}"
           - "XENIA_UPDATE_QUERY=${XENIA_UPDATE_QUERY}"
           - "XENIA_DATABASE_SCHEMA_PATH=${XENIA_DATABASE_SCHEMA_PATH}"
           - "XENIA_QUERY_UPSERT_PATH=${XENIA_QUERY_UPSERT_PATH}"
   ports:
       - "4000:4000"
   links:
      - mongodata

cayapp:
      - mongodata:mongo

cay:
   image: coralproject/cay
   environment:
       - "XENIA_URL=https://${FRONTEND_HOST}/xenia_demo/"
       - "PILLAR_URL=https://${FRONTEND_HOST}/pillar_demo/"
       - "ENV=staging"
       - "PROJECT=Coral Project"
       - "GAID=${GAID_VALUE}"
       - "AUTH_TOKEN=${AUTH_TOKEN_VALUE}"
   links:
       - pillarapp
       - xeniaapp

sponge:
    image: coralproject/sponge
    restart: always
    environment:
        - "STRATEGY_CONF=/usr/local/strategy.json"
        - "PILLAR_URL=http://${FRONTEND_HOST}:8080"
    volumes:
        - ./sponge/assets/strategy.json:/usr/local/strategy.json

proxy:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./proxy/:/etc/nginx/conf.d/
      - ./certs/:/etc/ssl/certs/
    links:
      - atollapp:atoll
      - pillarapp:pillar
      - xeniaapp:xenia
      - cayapp:cay
    ports:
      - "8080:80"
      - "443:443"
