mongodata:
  image: coralproject/mongodata
  environment:
    - "MONGO_DUMP=https://s3.amazonaws.com/coral-demo-dataset/dump.tar.gz"
    - "MONGO_USER=${MONGO_USER}"
    - "MONGO_PASS=${MONGO_PASS}"
    - "MONGO_DB=${MONGO_DB}"
  volumes:
    - /mongodata:/data/db
  ports:
    - "27017"

rabbitmq:
  image: rabbitmq:management
  environment:
    - "RABBITMQ_DEFAULT_USER=${RABBIT_USER}"
    - "RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}"
  ports:
    - "15672:15672"
    - "5672:5672"

pillar:
   image: coralproject/pillar
   environment:
           - "PILLAR_HOME=/opt/pillar"
           - "PILLAR_ADDRESS=:8080"
           - "MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/${MONGO_AUTHDB}"
           - "AMQP_URL=amqp://${RABBIT_USER}:${RABBIT_PASS}@rabbitmq:5672/"
   ports:
       - "8080:8080"
   links:
      - mongodata:mongo
      - rabbitmq

atoll:
   image: coralproject/atoll
   ports:
       - "8181:8181"
   links:
      - mongodata:mongo

xenia:
   image: coralproject/xenia
   environment:
           - "XENIA_MONGO_HOST=mongo:27017"
           - "XENIA_MONGO_AUTHDB=${MONGO_AUTHDB}"
           - "XENIA_MONGO_DB=${MONGO_DB}"
           - "XENIA_MONGO_USER=${MONGO_USER}"
           - "XENIA_MONGO_PASS=${MONGO_PASS}"
           - "XENIA_LOGGING_LEVEL=1"
           - "XENIA_HOST=:4000"
   ports:
       - "4000:4000"
   links:
      - mongodata:mongo

cay:
   image: coralproject/cay
   environment:
       - "XENIA_URL=https://${FRONTEND_HOST}/xenia_demo/"
       - "PILLAR_URL=https://${FRONTEND_HOST}/pillar_demo/"
       - "ENV=staging"
       - "PROJECT=Coral Project"
       - "GAID=${GAID_VALUE}"
       - "AUTH_TOKEN=${AUTH_TOKEN_VALUE}"
   links:
       - pillar
       - xenia

sponge:
    image: coralproject/sponge
    environment:
        - "STRATEGY_CONF=/usr/local/strategy.json"
        - "PILLAR_URL=http://${FRONTEND_HOST}:8080"
    volumes:
        - ./sponge/assets/strategy.json:/usr/local/strategy.json

proxy:
    image: nginx:stable-alpine
    volumes:
      - ./proxy/:/etc/nginx/conf.d/
      - ./certs/:/etc/ssl/certs/
    links:
      - atoll
      - pillar
      - xenia
      - cay
    ports:
      - "80:80"
      - "443:443"
